apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-processor
  labels:
    app: processor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50052
              protocol: TCP
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.kafka.brokers | quote }}
            - name: KAFKA_IN_TOPIC
              value: {{ .Values.kafka.in_topic | quote }}
            - name: KAFKA_OUT_TOPIC
              value: {{ .Values.kafka.out_topic | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
