// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/v1/processor/feature.proto

package processor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessedFeature represents the normalized data ready for ML analysis/Anomalous detection
type ProcessedFeature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for the processed event
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the original raw event
	OriginalEventId string `protobuf:"bytes,2,opt,name=original_event_id,json=originalEventId,proto3" json:"original_event_id,omitempty"`
	// Time the event was captured
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Source device information
	DeviceId string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Protocol string `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Generic normalized data (0.0 to 1.0)
	NormalizedValue float32 `protobuf:"fixed32,6,opt,name=normalized_value,json=normalizedValue,proto3" json:"normalized_value,omitempty"`
	// Protocol specific features (represented as a map for flexibility,
	// but some key fields are promoted for efficiency)
	NumericFeatures     map[string]float32 `protobuf:"bytes,7,rep,name=numeric_features,json=numericFeatures,proto3" json:"numeric_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	CategoricalFeatures map[string]string  `protobuf:"bytes,8,rep,name=categorical_features,json=categoricalFeatures,proto3" json:"categorical_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Modbus-specific promoted features
	ModbusFunctionCode    int32   `protobuf:"varint,9,opt,name=modbus_function_code,json=modbusFunctionCode,proto3" json:"modbus_function_code,omitempty"`
	ModbusRegisterAddress int32   `protobuf:"varint,10,opt,name=modbus_register_address,json=modbusRegisterAddress,proto3" json:"modbus_register_address,omitempty"`
	ModbusValues          []int32 `protobuf:"varint,11,rep,packed,name=modbus_values,json=modbusValues,proto3" json:"modbus_values,omitempty"`
	// Risk score calculated during normalization (0.0 = safe, 1.0 = highly suspicious)
	BaselineRiskScore float32 `protobuf:"fixed32,12,opt,name=baseline_risk_score,json=baselineRiskScore,proto3" json:"baseline_risk_score,omitempty"`
	// List of indicators triggered during normalization (e.g. "UNUSUAL_FUNCTION_CODE")
	RiskIndicators []string `protobuf:"bytes,13,rep,name=risk_indicators,json=riskIndicators,proto3" json:"risk_indicators,omitempty"`
	// Execution metadata
	ProcessorVersion string `protobuf:"bytes,14,opt,name=processor_version,json=processorVersion,proto3" json:"processor_version,omitempty"`
	// BACnet-specific promoted features
	BacnetObjectType         string `protobuf:"bytes,15,opt,name=bacnet_object_type,json=bacnetObjectType,proto3" json:"bacnet_object_type,omitempty"`
	BacnetObjectInstance     int32  `protobuf:"varint,16,opt,name=bacnet_object_instance,json=bacnetObjectInstance,proto3" json:"bacnet_object_instance,omitempty"`
	BacnetPropertyIdentifier string `protobuf:"bytes,17,opt,name=bacnet_property_identifier,json=bacnetPropertyIdentifier,proto3" json:"bacnet_property_identifier,omitempty"`
	BacnetPriority           int32  `protobuf:"varint,18,opt,name=bacnet_priority,json=bacnetPriority,proto3" json:"bacnet_priority,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ProcessedFeature) Reset() {
	*x = ProcessedFeature{}
	mi := &file_api_v1_processor_feature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedFeature) ProtoMessage() {}

func (x *ProcessedFeature) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_processor_feature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedFeature.ProtoReflect.Descriptor instead.
func (*ProcessedFeature) Descriptor() ([]byte, []int) {
	return file_api_v1_processor_feature_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessedFeature) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessedFeature) GetOriginalEventId() string {
	if x != nil {
		return x.OriginalEventId
	}
	return ""
}

func (x *ProcessedFeature) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ProcessedFeature) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ProcessedFeature) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProcessedFeature) GetNormalizedValue() float32 {
	if x != nil {
		return x.NormalizedValue
	}
	return 0
}

func (x *ProcessedFeature) GetNumericFeatures() map[string]float32 {
	if x != nil {
		return x.NumericFeatures
	}
	return nil
}

func (x *ProcessedFeature) GetCategoricalFeatures() map[string]string {
	if x != nil {
		return x.CategoricalFeatures
	}
	return nil
}

func (x *ProcessedFeature) GetModbusFunctionCode() int32 {
	if x != nil {
		return x.ModbusFunctionCode
	}
	return 0
}

func (x *ProcessedFeature) GetModbusRegisterAddress() int32 {
	if x != nil {
		return x.ModbusRegisterAddress
	}
	return 0
}

func (x *ProcessedFeature) GetModbusValues() []int32 {
	if x != nil {
		return x.ModbusValues
	}
	return nil
}

func (x *ProcessedFeature) GetBaselineRiskScore() float32 {
	if x != nil {
		return x.BaselineRiskScore
	}
	return 0
}

func (x *ProcessedFeature) GetRiskIndicators() []string {
	if x != nil {
		return x.RiskIndicators
	}
	return nil
}

func (x *ProcessedFeature) GetProcessorVersion() string {
	if x != nil {
		return x.ProcessorVersion
	}
	return ""
}

var File_api_v1_processor_feature_proto protoreflect.FileDescriptor

const file_api_v1_processor_feature_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/v1/processor/feature.proto\x12\x11otie.processor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x06\n" +
	"\x10ProcessedFeature\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11original_event_id\x18\x02 \x01(\tR\x0foriginalEventId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12)\n" +
	"\x10normalized_value\x18\x06 \x01(\x02R\x0fnormalizedValue\x12c\n" +
	"\x10numeric_features\x18\a \x03(\v28.otie.processor.v1.ProcessedFeature.NumericFeaturesEntryR\x0fnumericFeatures\x12o\n" +
	"\x14categorical_features\x18\b \x03(\v2<.otie.processor.v1.ProcessedFeature.CategoricalFeaturesEntryR\x13categoricalFeatures\x120\n" +
	"\x14modbus_function_code\x18\t \x01(\x05R\x12modbusFunctionCode\x126\n" +
	"\x17modbus_register_address\x18\n" +
	" \x01(\x05R\x15modbusRegisterAddress\x12#\n" +
	"\rmodbus_values\x18\v \x03(\x05R\fmodbusValues\x12.\n" +
	"\x13baseline_risk_score\x18\f \x01(\x02R\x11baselineRiskScore\x12'\n" +
	"\x0frisk_indicators\x18\r \x03(\tR\x0eriskIndicators\x12+\n" +
	"\x11processor_version\x18\x0e \x01(\tR\x10processorVersion\x1aB\n" +
	"\x14NumericFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1aF\n" +
	"\x18CategoricalFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B`Z^github.com/OmniNStack/OmniNStack-OTIE/api/v1/processor;processorb\x06proto3"

var (
	file_api_v1_processor_feature_proto_rawDescOnce sync.Once
	file_api_v1_processor_feature_proto_rawDescData []byte
)

func file_api_v1_processor_feature_proto_rawDescGZIP() []byte {
	file_api_v1_processor_feature_proto_rawDescOnce.Do(func() {
		file_api_v1_processor_feature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_processor_feature_proto_rawDesc), len(file_api_v1_processor_feature_proto_rawDesc)))
	})
	return file_api_v1_processor_feature_proto_rawDescData
}

var file_api_v1_processor_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_processor_feature_proto_goTypes = []any{
	(*ProcessedFeature)(nil),      // 0: otie.processor.v1.ProcessedFeature
	nil,                           // 1: otie.processor.v1.ProcessedFeature.NumericFeaturesEntry
	nil,                           // 2: otie.processor.v1.ProcessedFeature.CategoricalFeaturesEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_v1_processor_feature_proto_depIdxs = []int32{
	3, // 0: otie.processor.v1.ProcessedFeature.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: otie.processor.v1.ProcessedFeature.numeric_features:type_name -> otie.processor.v1.ProcessedFeature.NumericFeaturesEntry
	2, // 2: otie.processor.v1.ProcessedFeature.categorical_features:type_name -> otie.processor.v1.ProcessedFeature.CategoricalFeaturesEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_processor_feature_proto_init() }
func file_api_v1_processor_feature_proto_init() {
	if File_api_v1_processor_feature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_processor_feature_proto_rawDesc), len(file_api_v1_processor_feature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_processor_feature_proto_goTypes,
		DependencyIndexes: file_api_v1_processor_feature_proto_depIdxs,
		MessageInfos:      file_api_v1_processor_feature_proto_msgTypes,
	}.Build()
	File_api_v1_processor_feature_proto = out.File
	file_api_v1_processor_feature_proto_goTypes = nil
	file_api_v1_processor_feature_proto_depIdxs = nil
}
