// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/v1/processor/processor.proto

package processor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       string                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_api_v1_processor_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_processor_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_processor_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ProcessedData string                 `protobuf:"bytes,3,opt,name=processed_data,json=processedData,proto3" json:"processed_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_api_v1_processor_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_processor_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_processor_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessResponse) GetProcessedData() string {
	if x != nil {
		return x.ProcessedData
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_v1_processor_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_processor_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_processor_processor_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_v1_processor_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_processor_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_processor_processor_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_v1_processor_processor_proto protoreflect.FileDescriptor

const file_api_v1_processor_processor_proto_rawDesc = "" +
	"\n" +
	" api/v1/processor/processor.proto\x12\x11otie.processor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x0eProcessRequest\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\tR\arawData\"l\n" +
	"\x0fProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eprocessed_data\x18\x03 \x01(\tR\rprocessedData\"\x14\n" +
	"\x12HealthCheckRequest\"L\n" +
	"\x13HealthCheckResponse\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x01 \x01(\bR\tisHealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xc2\x01\n" +
	"\x10ProcessorService\x12P\n" +
	"\aProcess\x12!.otie.processor.v1.ProcessRequest\x1a\".otie.processor.v1.ProcessResponse\x12\\\n" +
	"\vCheckHealth\x12%.otie.processor.v1.HealthCheckRequest\x1a&.otie.processor.v1.HealthCheckResponseB`Z^github.com/OmniNStack/OmniNStack-OTIE/api/v1/processor;processorb\x06proto3"

var (
	file_api_v1_processor_processor_proto_rawDescOnce sync.Once
	file_api_v1_processor_processor_proto_rawDescData []byte
)

func file_api_v1_processor_processor_proto_rawDescGZIP() []byte {
	file_api_v1_processor_processor_proto_rawDescOnce.Do(func() {
		file_api_v1_processor_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_processor_processor_proto_rawDesc), len(file_api_v1_processor_processor_proto_rawDesc)))
	})
	return file_api_v1_processor_processor_proto_rawDescData
}

var file_api_v1_processor_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_processor_processor_proto_goTypes = []any{
	(*ProcessRequest)(nil),      // 0: otie.processor.v1.ProcessRequest
	(*ProcessResponse)(nil),     // 1: otie.processor.v1.ProcessResponse
	(*HealthCheckRequest)(nil),  // 2: otie.processor.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: otie.processor.v1.HealthCheckResponse
}
var file_api_v1_processor_processor_proto_depIdxs = []int32{
	0, // 0: otie.processor.v1.ProcessorService.Process:input_type -> otie.processor.v1.ProcessRequest
	2, // 1: otie.processor.v1.ProcessorService.CheckHealth:input_type -> otie.processor.v1.HealthCheckRequest
	1, // 2: otie.processor.v1.ProcessorService.Process:output_type -> otie.processor.v1.ProcessResponse
	3, // 3: otie.processor.v1.ProcessorService.CheckHealth:output_type -> otie.processor.v1.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_processor_processor_proto_init() }
func file_api_v1_processor_processor_proto_init() {
	if File_api_v1_processor_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_processor_processor_proto_rawDesc), len(file_api_v1_processor_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_processor_processor_proto_goTypes,
		DependencyIndexes: file_api_v1_processor_processor_proto_depIdxs,
		MessageInfos:      file_api_v1_processor_processor_proto_msgTypes,
	}.Build()
	File_api_v1_processor_processor_proto = out.File
	file_api_v1_processor_processor_proto_goTypes = nil
	file_api_v1_processor_processor_proto_depIdxs = nil
}
